backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Adjust based on your project
public_folder: "/img"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
