[[headers]]
  for = "/**"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/octet-stream"

[build]
  command = "npm run build" # Or your build command
  publish = "dist"          # Directory where built files are placed (e.g., dist, build, public)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
from = "/download/*"
to = "/download/:splat"
status = 200
force = true